import { execFile } from "child_process";
import * as fs from "fs/promises";
import * as path from "path";
import { config } from "../../config/env";
import { getDatabase } from "../../config/database";
import { rowToProject, type Project, type ProjectRow } from "../../entities/Project";
import { listAllRoutableProjectDomains, type ProjectDomain } from "../projectDomains";
import { invalidateNginxActiveStatus } from "./statusCache";
import { SELF_SIGNED_CERT_PATH, SELF_SIGNED_KEY_PATH } from "./selfSignedCert";

export const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/i;

const TEMPLATE_DIR = "templates";
const BACKUP_DIR = "backups";
const STATE_FILE = "state.json";
const FAILED_FILE = "failed.conf";
const DEFAULT_SITE = path.join("sites-available", "default");
const APP_NGINX_ENABLED_KEY = "nginx_app_enabled";
const APP_NGINX_DOMAIN_KEY = "nginx_app_domain";
const APP_NGINX_USE_SSL_KEY = "nginx_app_use_ssl";
const APP_ROUTE_NAME = "StackPort: MW VPS Manager";

// Phase 1.5 — which nginx instance StackPort validates/reloads against. "host"
// (default, unchanged today's behavior) uses systemctl/host nginx via sudo; a
// "container" switch uses `docker exec` against stackport-nginx (docker-compose.
// system.yml) instead — StackPort already has full Docker-socket access (Phase 1.1),
// so this needs no new privilege grant at all. Config *generation* (writing the
// actual files under config.nginxPath) is identical either way; only how validation/
// reload commands are issued changes. Switching requires NGINX_PATH to already point
// at the same host directory bind-mounted into the stackport-nginx container — see
// docker-compose.system.yml's comments.
const NGINX_RUNTIME_KEY = "nginx_runtime";
const NGINX_CONTAINER_NAME = "stackport-nginx";
export type NginxRuntime = "host" | "container";

export function getNginxRuntime(): NginxRuntime {
  const row = getDatabase().prepare("SELECT value FROM app_meta WHERE key = ?").get(NGINX_RUNTIME_KEY) as { value: string } | undefined;
  // Defaults to "container", not "host": stackport.sh (the only install path as of
  // Phase 1.9) never sets up a host nginx/certbot at all, so a fresh install with no
  // explicit app_meta row must behave as "container" from first boot — otherwise
  // ensureAppIngress() (appIngress.ts) silently no-ops on its "host" guard and the
  // app is never actually reachable through nginx at all (no self-signed cert, no
  // generated config) until someone manually flips this in a UI they can't yet
  // reach. An explicit row (e.g. a dev checkout that intentionally opted into host
  // mode before this default changed) is still honored either way.
  return row?.value === "host" ? "host" : "container";
}

export function setNginxRuntime(runtime: NginxRuntime): void {
  getDatabase()
    .prepare(`
      INSERT INTO app_meta (key, value, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)
      ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
    `)
    .run(NGINX_RUNTIME_KEY, runtime);
}

// Phase 1.6 — fixed, absolute host path (not repo-relative): both nginx (which serves
// from it) and certbot's `docker run` invocations (which write into it) need to agree
// on the exact same host-filesystem location, and since certbot is invoked via
// Docker-out-of-Docker from inside the StackPort container, any relative path would
// resolve against the wrong filesystem view — only an absolute path is unambiguous
// regardless of which container issues the docker command. Matches the host
// directory convention from stackport_host_lifecycle.md's target layout.
export const CERTBOT_WEBROOT_PATH = "/var/lib/stackport/certbot-webroot";

const NGINX_LOG_FORMAT_NAME = "stackport";
// Extended combined format: adds "$host" and $request_time after the standard combined fields.
// Enables per-domain traffic breakdown and response-time percentiles in metrics.
// Defined at http level; referenced by access_log inside each server block (not at http level,
// which would double-log since nginx.conf already has an access_log directive there).
const NGINX_LOG_FORMAT_BLOCK = `log_format ${NGINX_LOG_FORMAT_NAME} '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$host" $request_time';`;

const DEFAULT_GENERAL_TEMPLATE = `# ============================================================
# Generated by StackPort: MW VPS Manager
# Edit this general config at: templates/general.conf
# ============================================================

${NGINX_LOG_FORMAT_BLOCK}

# Configured routed domains
{{domainList}}
{{subdomainList}}

# HTTP fallback: keep unknown hosts on HTTPS.
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}

{{httpsDefaultServerBlock}}`;

// Default value of the {{httpsDefaultServerBlock}} placeholder above — the exact
// text that block used to be hardcoded to before Phase 1.9's domain-less bootstrap
// support. Used both as generateNginxConfig()'s fallback (whenever there's no
// self-signed bootstrap cert to serve) and, unchanged, as the migration target in
// ensureTemplates() below for any general.conf written before this change.
const REJECT_UNKNOWN_TLS_BLOCK = `# HTTPS fallback: reject unknown TLS hosts.
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name _;

    ssl_reject_handshake on;
}`;

const LEGACY_PROJECT_TEMPLATE = `# ============================================================
# {{name}}
# {{domain}}
# ============================================================

server {
    listen 80;
    listen [::]:80;

    server_name {{domain}};

    return 301 https://{{domain}}$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name {{domain}};

    ssl_certificate {{certBase}}/fullchain.pem;
    ssl_certificate_key {{certBase}}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
{{locationBlock}}
}`;

const PREVIOUS_DEFAULT_PROJECT_TEMPLATE = `# ============================================================
# {{name}}
# {{domain}}
# ============================================================

{{httpServerBlock}}

{{httpsServerBlock}}`;

const DEFAULT_PROJECT_TEMPLATE = `# ============================================================
# {{name}}
# {{domain}}
# ============================================================

{{wwwHttpRedirectBlock}}

{{httpServerBlock}}

{{httpsServerBlock}}

{{wwwHttpsRedirectBlock}}`;

export interface NginxApplyResult {
  ok: boolean;
  mode: "real";
  targetPath: string;
  backupPath: string | null;
  restored: boolean;
  output: string;
}

export interface NginxLayerStatus {
  mode: "real";
  rootPath: string;
  targetPath: string;
  generalTemplatePath: string;
  projectTemplatePath: string;
  backupDir: string;
  exists: boolean;
  failedConfigExists: boolean;
  sizeBytes: number | null;
  domains: string[];
  domainList: string[];
  subdomainList: string[];
  routes: NginxRouteSummary[];
  backupCount: number;
  lastOperation: NginxState | null;
  app: NginxAppConfig;
  fixedBlockPath: string;
  domainTemplatePath: string;
}

export interface NginxAppConfig {
  enabled: boolean;
  domain: string;
  port: number;
  useSsl: boolean;
}

export interface NginxRouteSummary {
  project: string;
  domain: string;
  service: string;
  port: number;
}

export type NginxDocumentKind = "generated" | "general" | "project" | "failed";

export interface NginxDocument {
  kind: NginxDocumentKind;
  path: string;
  editable: boolean;
  content: string;
  updatedAt: string | null;
  sizeBytes: number | null;
}

interface NginxState {
  ok: boolean;
  mode: "real";
  targetPath: string;
  backupPath: string | null;
  restored: boolean;
  output: string;
  updatedAt: string;
  restartCount: number;
}

interface RunResult {
  stdout: string;
  stderr: string;
  ok: boolean;
  notFound: boolean;
}

interface NginxTarget {
  name: string;
  domain: string;
  /** Compose service name this domain routes to — Docker DNS over the shared
   *  stackport-proxy network (composeNetworking.ts), not a host port (Phase 1.7). */
  service: string;
  containerPort: number;
  useSsl: boolean;
  includeWwwRedirect: boolean;
  /** Raw directives appended inside the proxying `location /` block — e.g. client_max_body_size, proxy_read_timeout. */
  extraConfig: string;
  /** Raw server-level blocks (e.g. additional `location` blocks) appended after `location /`, HTTPS server only. Supports `{{PORT}}`, substituted with containerPort. */
  extraBlocks: string;
}

function resolveRoot(): string {
  return path.resolve(config.nginxPath);
}

function paths() {
  const root = resolveRoot();
  return {
    root,
    target: path.join(root, DEFAULT_SITE),
    generalTemplate: path.join(root, TEMPLATE_DIR, "general.conf"),
    projectTemplate: path.join(root, TEMPLATE_DIR, "project.conf"),
    fixedBlock: path.join(root, TEMPLATE_DIR, "fixed.conf"),
    domainTemplate: path.join(root, TEMPLATE_DIR, "domain.conf"),
    backupDir: path.join(root, BACKUP_DIR),
    state: path.join(root, STATE_FILE),
    failedConfig: path.join(root, FAILED_FILE),
  };
}

function documentPath(kind: NginxDocumentKind): string {
  const p = paths();
  if (kind === "generated") return p.target;
  if (kind === "failed") return p.failedConfig;
  if (kind === "general") return p.generalTemplate;
  return p.projectTemplate;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function ensureTemplates(): Promise<void> {
  const p = paths();
  await fs.mkdir(path.dirname(p.generalTemplate), { recursive: true });
  if (!(await fileExists(p.generalTemplate))) {
    await fs.writeFile(p.generalTemplate, DEFAULT_GENERAL_TEMPLATE + "\n", "utf8");
  } else {
    let existing = await fs.readFile(p.generalTemplate, "utf8");
    let migrated = false;
    // Upgrade: prepend log_format block if the template predates this feature
    if (!existing.includes(`log_format ${NGINX_LOG_FORMAT_NAME}`)) {
      existing = NGINX_LOG_FORMAT_BLOCK + "\n\n" + existing;
      migrated = true;
    }
    // Upgrade: replace the old hardcoded reject-unknown-TLS block with the
    // {{httpsDefaultServerBlock}} placeholder (Phase 1.9 — self-signed bootstrap
    // support needs this to be dynamic, see generateNginxConfig()).
    if (!existing.includes("{{httpsDefaultServerBlock}}") && existing.includes(REJECT_UNKNOWN_TLS_BLOCK)) {
      existing = existing.replace(REJECT_UNKNOWN_TLS_BLOCK, "{{httpsDefaultServerBlock}}");
      migrated = true;
    }
    if (migrated) {
      await fs.writeFile(p.generalTemplate, existing, "utf8");
    }
  }
  if (!(await fileExists(p.projectTemplate))) {
    await fs.writeFile(p.projectTemplate, DEFAULT_PROJECT_TEMPLATE + "\n", "utf8");
  } else {
    const existing = await fs.readFile(p.projectTemplate, "utf8");
    if (existing.trim() === LEGACY_PROJECT_TEMPLATE.trim() || existing.trim() === PREVIOUS_DEFAULT_PROJECT_TEMPLATE.trim()) {
      await fs.writeFile(p.projectTemplate, DEFAULT_PROJECT_TEMPLATE + "\n", "utf8");
    }
  }
}

/** Indents each non-empty line of a raw directive block to match the location body (8 spaces). */
function indentExtraConfig(extraConfig: string): string {
  const lines = extraConfig.split("\n").map((line) => line.trim()).filter(Boolean);
  if (lines.length === 0) return "";
  return "\n" + lines.map((line) => `        ${line}`).join("\n");
}

/**
 * Re-indents a raw block of nginx config (e.g. one or more `location { ... }` blocks) to the
 * server body level (4 spaces), preserving the relative nesting the user typed by dedenting to
 * the shallowest line first. Unlike indentExtraConfig, this content isn't flattened to one
 * level — it may contain its own `{ }` nesting.
 */
function indentExtraBlocks(extraBlocks: string): string {
  const rawLines = extraBlocks.replace(/\r\n/g, "\n").split("\n");
  const nonEmpty = rawLines.filter((line) => line.trim().length > 0);
  if (nonEmpty.length === 0) return "";
  const minIndent = Math.min(...nonEmpty.map((line) => line.match(/^ */)?.[0].length ?? 0));
  return "\n\n" + nonEmpty.map((line) => `    ${line.slice(minIndent)}`).join("\n");
}

/** Substitutes project template vars (currently just `{{PORT}}`) into a project's raw extraBlocks, then indents it for embedding in the HTTPS server block. */
function renderExtraBlocks(target: NginxTarget): string {
  if (!target.extraBlocks.trim()) return "";
  const substituted = target.extraBlocks.replace(/\{\{PORT\}\}/g, String(target.containerPort));
  return indentExtraBlocks(substituted);
}

function locationBlock(target: NginxTarget): string {
  const upstreamUrl = `http://${target.service}:${target.containerPort}`;
  // Resolve at request time so a stopped/not-yet-deployed workload cannot prevent
  // nginx from loading Stackport's own admin route. Also refresh DNS after recreation.
  const proxy = getNginxRuntime() === "container"
    ? `resolver 127.0.0.11 valid=10s ipv6=off;\n        set $stackport_upstream ${upstreamUrl};\n        proxy_pass $stackport_upstream;`
    : `proxy_pass ${upstreamUrl};`;

  return `
    location / {
        ${proxy}
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;${indentExtraConfig(target.extraConfig)}
    }`;
}

async function certificateExists(domain: string): Promise<boolean> {
  const certBase = path.join("/etc/letsencrypt/live", domain);
  const files = [path.join(certBase, "fullchain.pem"), path.join(certBase, "privkey.pem")];

  if (getNginxRuntime() === "container") {
    const checks = await Promise.all(files.map((file) => run("docker", ["exec", NGINX_CONTAINER_NAME, "test", "-f", file])));
    return checks.every((check) => check.ok);
  }

  const direct = await Promise.all(files.map((file) => fileExists(file)));
  if (direct.every(Boolean)) return true;

  const checks = await Promise.all(files.map((file) => {
    const command = privileged("test", ["-f", file]);
    return run(command.cmd, command.args);
  }));
  return checks.every((check) => check.ok);
}

// `^~` gives this prefix match priority over both `location /`'s proxy and the plain
// Redirects belong inside `location /` so server-level rewrite processing cannot
// intercept ACME HTTP-01 challenges during issuance or renewal.
function acmeChallengeLocation(): string {
  return `
    location ^~ /.well-known/acme-challenge/ {
        root ${CERTBOT_WEBROOT_PATH};
        default_type "text/plain";
    }`;
}

function httpServerBlock(target: NginxTarget, hasCertificate: boolean): string {
  const domain = target.domain;
  const body = hasCertificate
    ? `    location / {\n        return 301 https://${domain}$request_uri;\n    }`
    : `    access_log /var/log/nginx/access.log ${NGINX_LOG_FORMAT_NAME};\n${locationBlock(target).replace(/^\n/, "").trimEnd()}`;

  return `server {
    listen 80;
    listen [::]:80;

    server_name ${domain};
${acmeChallengeLocation()}

${body}
}`;
}

function wwwDomain(target: NginxTarget): string | null {
  if (!target.includeWwwRedirect || target.domain.startsWith("www.")) return null;
  return `www.${target.domain}`;
}

function wwwHttpRedirectBlock(target: NginxTarget, hasCertificate: boolean): string {
  const www = wwwDomain(target);
  if (!www) return "";
  const scheme = hasCertificate ? "https" : "http";

  return `server {
    listen 80;
    listen [::]:80;

    server_name ${www};
${acmeChallengeLocation()}
    location / {
        return 301 ${scheme}://${target.domain}$request_uri;
    }
}`;
}

// Phase 1.9 — the very first login on a domain-less (raw-IP) install has to happen
// over HTTPS with no real domain and no Let's Encrypt cert yet possible (LE doesn't
// issue for bare IPs). Renders the app itself as the HTTPS default_server, using the
// self-signed cert services/nginx/selfSignedCert.ts generates once at boot. Reuses
// locationBlock() exactly like appRouteTarget()'s normal domain-matched block does —
// only the listen/server_name/cert lines differ (default_server + server_name "_"
// instead of a real hostname, self-signed paths instead of a letsencrypt/live one).
function selfSignedDefaultServerBlock(): string {
  const target: NginxTarget = {
    name: APP_ROUTE_NAME,
    domain: "_",
    service: STACKPORT_APP_SERVICE,
    containerPort: config.port,
    useSsl: true,
    includeWwwRedirect: false,
    extraConfig: "",
    extraBlocks: "",
  };

  return `# HTTPS fallback: no app domain configured yet — serve StackPort itself over
# the self-signed bootstrap certificate so first login is still HTTPS. Superseded
# automatically once a real app domain is configured (see appRouteTarget()).
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;

    server_name _;

    ssl_certificate ${SELF_SIGNED_CERT_PATH};
    ssl_certificate_key ${SELF_SIGNED_KEY_PATH};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/access.log ${NGINX_LOG_FORMAT_NAME};
${locationBlock(target)}
}`;
}

function httpsServerBlock(target: NginxTarget): string {
  const domain = target.domain;
  const certBase = `/etc/letsencrypt/live/${domain}`;

  return `server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ${domain};

    ssl_certificate ${certBase}/fullchain.pem;
    ssl_certificate_key ${certBase}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/access.log ${NGINX_LOG_FORMAT_NAME};
${locationBlock(target)}${renderExtraBlocks(target)}
}`;
}

function wwwHttpsRedirectBlock(target: NginxTarget): string {
  const www = wwwDomain(target);
  if (!www) return "";
  const certBase = `/etc/letsencrypt/live/${target.domain}`;

  return `server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name ${www};

    ssl_certificate ${certBase}/fullchain.pem;
    ssl_certificate_key ${certBase}/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    return 301 https://${target.domain}$request_uri;
}`;
}

async function renderDomainBlock(template: string, target: NginxTarget): Promise<string> {
  const domain = target.domain;
  const hasCertificate = target.useSsl && domain ? await certificateExists(domain) : false;
  const wwwRedirect = target.includeWwwRedirect ? wwwDomain(target) ?? "" : "";
  const upstreamUrl = `http://${target.service}:${target.containerPort}`;
  const values: Record<string, string> = {
    name: target.name,
    domain,
    wwwDomain: wwwRedirect,
    service: target.service,
    containerPort: String(target.containerPort),
    upstreamUrl,
    url: upstreamUrl,
    certBase: `/etc/letsencrypt/live/${domain}`,
    locationBlock: locationBlock(target),
    wwwHttpRedirectBlock: wwwHttpRedirectBlock(target, hasCertificate),
    httpServerBlock: httpServerBlock(target, hasCertificate),
    httpsServerBlock: hasCertificate ? httpsServerBlock(target) : "",
    wwwHttpsRedirectBlock: hasCertificate ? wwwHttpsRedirectBlock(target) : "",
    hasCertificate: hasCertificate ? "true" : "false",
    includeWwwRedirect: target.includeWwwRedirect ? "true" : "false",
  };

  return template.replace(/\{\{(name|domain|wwwDomain|service|containerPort|upstreamUrl|url|certBase|locationBlock|wwwHttpRedirectBlock|httpServerBlock|httpsServerBlock|wwwHttpsRedirectBlock|hasCertificate|includeWwwRedirect)\}\}/g, (_match, key: string) => values[key] ?? "");
}

async function loadProjects(): Promise<Project[]> {
  const rows = getDatabase()
    .prepare("SELECT * FROM projects WHERE paused = 0 ORDER BY name ASC")
    .all() as ProjectRow[];
  return rows.map(rowToProject);
}

export function getNginxAppConfig(): NginxAppConfig {
  const rows = getDatabase()
    .prepare("SELECT key, value FROM app_meta WHERE key IN (?, ?, ?)")
    .all(APP_NGINX_ENABLED_KEY, APP_NGINX_DOMAIN_KEY, APP_NGINX_USE_SSL_KEY) as Array<{ key: string; value: string }>;
  const values = new Map(rows.map((row) => [row.key, row.value]));
  return {
    enabled: values.get(APP_NGINX_ENABLED_KEY) === "1",
    domain: values.get(APP_NGINX_DOMAIN_KEY) ?? "",
    port: config.port,
    useSsl: values.get(APP_NGINX_USE_SSL_KEY) !== "0",
  };
}

export function setNginxAppConfig(input: { enabled: boolean; domain: string; useSsl?: boolean }): NginxAppConfig {
  const domain = input.domain.trim().toLowerCase();
  if (input.enabled && !DOMAIN_RE.test(domain)) {
    throw new Error("domain must be a valid hostname before enabling app Nginx publishing");
  }

  const db = getDatabase();
  if (input.enabled) {
    const portConflict = db.prepare("SELECT name FROM projects WHERE internal_port = ? LIMIT 1").get(config.port) as { name: string } | undefined;
    if (portConflict) {
      throw new Error(`Cannot enable app Nginx publishing because project "${portConflict.name}" already uses backend port ${config.port}`);
    }
    const domainConflict = db.prepare(
      "SELECT p.name AS name FROM project_domains pd JOIN projects p ON p.id = pd.project_id WHERE lower(pd.domain) = lower(?) LIMIT 1"
    ).get(domain) as { name: string } | undefined;
    if (domainConflict) {
      throw new Error(`Cannot enable app Nginx publishing because project "${domainConflict.name}" already uses ${domain}`);
    }
  }

  const now = new Date().toISOString();
  const upsert = db.prepare(`
    INSERT INTO app_meta (key, value, updated_at) VALUES (?, ?, ?)
    ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
  `);
  upsert.run(APP_NGINX_ENABLED_KEY, input.enabled ? "1" : "0", now);
  upsert.run(APP_NGINX_DOMAIN_KEY, domain, now);
  upsert.run(APP_NGINX_USE_SSL_KEY, input.useSsl === false ? "0" : "1", now);

  return getNginxAppConfig();
}

// The compose *service* name StackPort's own container runs as in docker-compose.
// system.yml (not container_name — Docker DNS over a shared network resolves by
// service name). Reachable from stackport-nginx once both join stackport-proxy.
const STACKPORT_APP_SERVICE = "stackport";

function appRouteTarget(appConfig: NginxAppConfig = getNginxAppConfig()): NginxTarget | null {
  if (!appConfig.enabled || !appConfig.domain) return null;
  return {
    name: APP_ROUTE_NAME,
    domain: appConfig.domain,
    service: STACKPORT_APP_SERVICE,
    containerPort: appConfig.port,
    useSsl: appConfig.useSsl,
    includeWwwRedirect: false,
    extraConfig: "",
    extraBlocks: "",
  };
}

/** One NginxTarget per routed (project, domain) pair — each domain gets its own full
 *  block set (server_name/cert/www-redirect), routing to whichever service/port that
 *  specific domain is configured for (Phase 1.7 — domain -> service -> container_port,
 *  no longer one shared internalPort per project). A domain with no service/port
 *  configured yet is skipped entirely — nothing to route to. includeWwwRedirect's
 *  apex check runs across every routed domain from every project, same as before —
 *  it was already domain-string-based, not project-based. */
function projectRouteTargets(projects: Project[], domainsByProject: Map<number, ProjectDomain[]>): NginxTarget[] {
  const isRouted = (pd: ProjectDomain): pd is ProjectDomain & { containerPort: number } => !!pd.service && !!pd.containerPort;
  const allDomains = projects.flatMap((project) => (domainsByProject.get(project.id) ?? []).filter(isRouted).map((pd) => pd.domain));
  const apexDomains = new Set(splitDomainLists(allDomains).domainList);

  return projects.flatMap((project) =>
    (domainsByProject.get(project.id) ?? []).filter(isRouted).map((pd) => ({
      name: project.name,
      domain: pd.domain,
      service: pd.service,
      containerPort: pd.containerPort,
      useSsl: pd.useSsl,
      includeWwwRedirect: apexDomains.has(pd.domain) && !allDomains.includes(`www.${pd.domain}`),
      extraConfig: project.nginxExtraConfig ?? "",
      extraBlocks: project.nginxExtraBlocks ?? "",
    }))
  );
}

async function routeTargets(projects: Project[]): Promise<NginxTarget[]> {
  const appTarget = appRouteTarget();
  const domainsByProject = listAllRoutableProjectDomains();
  return [...(appTarget ? [appTarget] : []), ...projectRouteTargets(projects, domainsByProject)];
}

function splitDomainLists(domains: string[]): { domainList: string[]; subdomainList: string[] } {
  const domainSet = new Set(domains);
  const subdomainList: string[] = [];
  const domainList: string[] = [];

  for (const domain of domains) {
    const parts = domain.split(".");
    const hasProjectParent = parts.some((_part, index) => {
      if (index === 0) return false;
      return domainSet.has(parts.slice(index).join("."));
    });

    if (hasProjectParent) {
      subdomainList.push(domain);
    } else {
      domainList.push(domain);
    }
  }

  return { domainList, subdomainList };
}

function listComment(label: string, values: string[]): string {
  const items = values.length > 0 ? values.map((value) => `# - ${value}`).join("\n") : "# - none";
  return `# ${label}:\n${items}`;
}

export async function generateNginxConfig(projects: Project[]): Promise<string> {
  await ensureTemplates();
  const p = paths();
  const [generalTemplate, projectTemplate, targets, selfSignedReady] = await Promise.all([
    fs.readFile(p.generalTemplate, "utf8"),
    fs.readFile(p.projectTemplate, "utf8"),
    routeTargets(projects),
    Promise.all([fileExists(SELF_SIGNED_CERT_PATH), fileExists(SELF_SIGNED_KEY_PATH)]).then(([cert, key]) => cert && key),
  ]);
  const allDomains = targets.map((target) => target.domain).sort((a, b) => a.localeCompare(b));
  const lists = splitDomainLists(allDomains);
  // App domain not configured yet + a self-signed cert exists (Phase 1.9 bootstrap,
  // services/appIngress.ts) -> serve the app itself as the HTTPS default_server so
  // first login works over a raw IP. Once a real app domain is set, appRouteTarget()
  // already produces its own domain-matched block and this reverts to rejecting
  // unmatched hosts, same as before Phase 1.9.
  const appConfigured = !!getNginxAppConfig().domain;
  const httpsDefaultServerBlock = !appConfigured && selfSignedReady
    ? selfSignedDefaultServerBlock()
    : REJECT_UNKNOWN_TLS_BLOCK;
  const generalBlock = generalTemplate
    .replace(/\{\{domainList\}\}/g, listComment("Domains", lists.domainList))
    .replace(/\{\{subdomainList\}\}/g, listComment("Subdomains", lists.subdomainList))
    .replace(/\{\{allDomainList\}\}/g, listComment("All routed domains", allDomains))
    .replace(/\{\{httpsDefaultServerBlock\}\}/g, httpsDefaultServerBlock);
  const blocks = (await Promise.all(targets.map((target) => renderDomainBlock(projectTemplate, target))))
    .map((block) => block.trimEnd())
    .join("\n\n");

  return [generalBlock.trimEnd(), blocks.trimEnd()].filter(Boolean).join("\n\n") + "\n";
}

async function run(cmd: string, args: string[], timeoutMs = 12_000): Promise<RunResult> {
  return new Promise((resolve) => {
    execFile(cmd, args, { timeout: timeoutMs, maxBuffer: 4 * 1024 * 1024 }, (err, stdout, stderr) => {
      const notFound = !!(err && (err as NodeJS.ErrnoException).code === "ENOENT");
      resolve({ stdout, stderr, ok: !err, notFound });
    });
  });
}

function privileged(cmd: string, args: string[]): { cmd: string; args: string[] } {
  if (typeof process.getuid === "function" && process.getuid() === 0) {
    return { cmd, args };
  }
  return { cmd: "sudo", args: ["-n", cmd, ...args] };
}

/** Wraps an already-built nginx CLI invocation for either runtime: "host" runs it
 *  (possibly sudo-wrapped) directly against the host's own nginx/systemctl, exactly
 *  as before; "container" runs the identical nginx-side arguments through
 *  `docker exec` against stackport-nginx instead — using the docker.sock access
 *  StackPort's own container already has, not sudo. */
function nginxCommand(cmd: string, args: string[]): { cmd: string; args: string[] } {
  if (getNginxRuntime() === "container") {
    return { cmd: "docker", args: ["exec", NGINX_CONTAINER_NAME, cmd, ...args] };
  }
  return privileged(cmd, args);
}

async function validateCurrentFile(): Promise<RunResult> {
  const command = nginxCommand("nginx", ["-t"]);
  return run(command.cmd, command.args);
}

async function validateCandidateFile(candidatePath: string): Promise<RunResult> {
  const p = paths();
  const tempMain = path.join(p.backupDir, `candidate.${Date.now()}.nginx.conf`);
  const mimeTypes = (await fileExists(path.join(p.root, "mime.types")))
    ? path.join(p.root, "mime.types")
    : "/etc/nginx/mime.types";
  const includeMimeTypes = await fileExists(mimeTypes) ? `    include ${mimeTypes};\n` : "";
  const tempConfig = `events {}

http {
${includeMimeTypes}    include ${candidatePath};
}
`;

  await fs.mkdir(p.backupDir, { recursive: true });
  await fs.writeFile(tempMain, tempConfig, "utf8");
  const command = nginxCommand("nginx", ["-t", "-c", tempMain]);
  const result = await run(command.cmd, command.args);
  await fs.rm(tempMain, { force: true }).catch(() => undefined);
  return result;
}

async function restartNginx(): Promise<RunResult> {
  // Reload itself isn't just a differently-wrapped version of the same command here
  // (unlike validate, above) — the container has no systemd/systemctl at all, so
  // "container" mode reloads nginx directly via its own `-s reload` instead.
  const command = getNginxRuntime() === "container"
    ? { cmd: "docker", args: ["exec", NGINX_CONTAINER_NAME, "nginx", "-s", "reload"] }
    : privileged("systemctl", ["reload", "nginx"]);
  return run(command.cmd, command.args);
}

async function readState(): Promise<NginxState | null> {
  try {
    return JSON.parse(await fs.readFile(paths().state, "utf8")) as NginxState;
  } catch {
    return null;
  }
}

async function writeState(result: NginxApplyResult): Promise<void> {
  const previous = await readState();
  const state: NginxState = {
    ...result,
    updatedAt: new Date().toISOString(),
    restartCount: result.ok ? (previous?.restartCount ?? 0) + 1 : (previous?.restartCount ?? 0),
  };
  await fs.mkdir(path.dirname(paths().state), { recursive: true });
  await fs.writeFile(paths().state, JSON.stringify(state, null, 2) + "\n", "utf8");
}

async function backupCurrentFile(): Promise<string | null> {
  const p = paths();
  if (!(await fileExists(p.target))) return null;

  await fs.mkdir(p.backupDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = path.join(p.backupDir, `default.${stamp}.bak`);
  await fs.copyFile(p.target, backupPath);
  return backupPath;
}

async function restoreBackup(backupPath: string | null): Promise<boolean> {
  if (!backupPath) {
    await fs.rm(paths().target, { force: true });
    return true;
  }
  await fs.copyFile(backupPath, paths().target);
  return true;
}

/** Single choke point for every nginx config mutation in the app (project/domain
 *  changes, manual Apply/Reload, certbot actions, MCP tools) — invalidates the
 *  cached "active" status once per apply attempt, regardless of outcome, since a
 *  reload can flip active/inactive either way. */
export async function writeNginxConfig(): Promise<NginxApplyResult> {
  const result = await writeNginxConfigImpl();
  invalidateNginxActiveStatus();
  return result;
}

async function writeNginxConfigImpl(): Promise<NginxApplyResult> {
  const p = paths();
  const projects = await loadProjects();
  const content = await generateNginxConfig(projects);
  const candidatePath = path.join(p.backupDir, `candidate.${Date.now()}.conf`);

  await fs.mkdir(path.dirname(p.target), { recursive: true });
  await fs.mkdir(p.backupDir, { recursive: true });
  await fs.writeFile(candidatePath, content, "utf8");

  const validation = await validateCandidateFile(candidatePath);
  const validationOutput = (validation.stderr || validation.stdout).trim();
  if (!validation.ok) {
    await fs.copyFile(candidatePath, p.failedConfig).catch(() => undefined);
    await fs.rm(candidatePath, { force: true }).catch(() => undefined);
    const result: NginxApplyResult = {
      ok: false,
      mode: "real",
      targetPath: p.target,
      backupPath: null,
      restored: false,
      output: validationOutput || "nginx validation failed",
    };
    await writeState(result);
    return result;
  }

  const backupPath = await backupCurrentFile();
  await fs.copyFile(candidatePath, p.target);
  await fs.rm(candidatePath, { force: true }).catch(() => undefined);

  const currentValidation = await validateCurrentFile();
  const currentValidationOutput = (currentValidation.stderr || currentValidation.stdout).trim();
  if (!currentValidation.ok) {
    await fs.writeFile(p.failedConfig, content, "utf8").catch(() => undefined);
    await restoreBackup(backupPath);
    const result: NginxApplyResult = {
      ok: false,
      mode: "real",
      targetPath: p.target,
      backupPath,
      restored: true,
      output: currentValidationOutput || "nginx validation failed after replacing config",
    };
    await writeState(result);
    return result;
  }

  const restart = await restartNginx();
  const restartOutput = (restart.stderr || restart.stdout).trim();
  if (!restart.ok) {
    await fs.writeFile(p.failedConfig, content, "utf8").catch(() => undefined);
    await restoreBackup(backupPath);
    const result: NginxApplyResult = {
      ok: false,
      mode: "real",
      targetPath: p.target,
      backupPath,
      restored: true,
      output: [currentValidationOutput, restartOutput || "nginx reload failed"].filter(Boolean).join("\n"),
    };
    await writeState(result);
    return result;
  }

  await fs.rm(p.failedConfig, { force: true }).catch(() => undefined);
  const result: NginxApplyResult = {
    ok: true,
    mode: "real",
    targetPath: p.target,
    backupPath,
    restored: false,
    output: [currentValidationOutput, restartOutput].filter(Boolean).join("\n"),
  };
  await writeState(result);
  return result;
}

export async function testNginxConfig(): Promise<{ ok: boolean; output: string }> {
  await ensureTemplates().catch(() => undefined);
  if (!(await fileExists(paths().target))) {
    return { ok: false, output: `No generated config found at ${paths().target}` };
  }
  const result = await validateCurrentFile();
  return { ok: result.ok, output: (result.stderr || result.stdout).trim() };
}

export async function reloadNginx(): Promise<NginxApplyResult> {
  return writeNginxConfig();
}

export async function getNginxLayerStatus(): Promise<NginxLayerStatus> {
  await ensureTemplates().catch(() => undefined);
  const p = paths();
  const [exists, failedConfigExists, projects, lastOperation] = await Promise.all([
    fileExists(p.target),
    fileExists(p.failedConfig),
    loadProjects(),
    readState(),
  ]);

  let sizeBytes: number | null = null;
  if (exists) {
    sizeBytes = (await fs.stat(p.target)).size;
  }

  let backupCount = 0;
  try {
    backupCount = (await fs.readdir(p.backupDir)).filter((name) => name.endsWith(".bak")).length;
  } catch {
    backupCount = 0;
  }

  const app = getNginxAppConfig();
  const targets = await routeTargets(projects);
  const domains = targets.map((target) => target.domain).sort((a, b) => a.localeCompare(b));
  const lists = splitDomainLists(domains);
  const routes = targets
    .map((target) => ({ project: target.name, domain: target.domain, service: target.service, port: target.containerPort }))
    .sort((a, b) => a.domain.localeCompare(b.domain));

  return {
    mode: "real",
    rootPath: p.root,
    targetPath: p.target,
    generalTemplatePath: p.generalTemplate,
    projectTemplatePath: p.projectTemplate,
    backupDir: p.backupDir,
    exists,
    failedConfigExists,
    sizeBytes,
    domains,
    domainList: lists.domainList,
    subdomainList: lists.subdomainList,
    routes,
    backupCount,
    lastOperation,
    app,
    fixedBlockPath: p.generalTemplate,
    domainTemplatePath: p.projectTemplate,
  };
}

export async function readNginxDocument(kind: NginxDocumentKind): Promise<NginxDocument> {
  if (kind !== "generated" && kind !== "failed") await ensureTemplates().catch(() => undefined);
  const filePath = documentPath(kind);
  const exists = await fileExists(filePath);

  if (!exists) {
    return {
      kind,
      path: filePath,
      editable: kind !== "generated" && kind !== "failed",
      content: "",
      updatedAt: null,
      sizeBytes: null,
    };
  }

  const [content, stat] = await Promise.all([
    fs.readFile(filePath, "utf8"),
    fs.stat(filePath),
  ]);

  return {
    kind,
    path: filePath,
    editable: kind !== "generated" && kind !== "failed",
    content,
    updatedAt: stat.mtime.toISOString(),
    sizeBytes: stat.size,
  };
}

export async function writeNginxTemplate(kind: Exclude<NginxDocumentKind, "generated">, content: string): Promise<NginxDocument> {
  await ensureTemplates();
  const filePath = documentPath(kind);
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf8");
  return readNginxDocument(kind);
}
