import crypto from "crypto";
import bcrypt from "bcryptjs";
import { getDatabase } from "../config/database";
import { config } from "../config/env";

const BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const INSTALLATION_INITIALIZED_KEY = "installation_initialized";
const ADMIN_USERNAME_KEY = "admin_username";
export const BOOTSTRAP_CREDENTIAL_TTL_MS = 24 * 60 * 60 * 1000;
export const RECOVERY_CREDENTIAL_TTL_MS = 30 * 60 * 1000;

export type SetupCredentialKind = "bootstrap" | "recovery";

interface SetupCredentialRow {
  id: number;
  kind: SetupCredentialKind;
  username: string;
  password_hash: string;
  created_at: string;
  expires_at: string;
  consumed_at: string | null;
}

// RFC4648 base32, no padding — matches stackport_host_lifecycle.md §5.1's
// `openssl rand 10 | base32 | tr -d '='` example (~80 bits from 10 random bytes),
// chosen over base64url so the credential avoids visually ambiguous characters
// and reads/dictates cleanly over a terminal.
function base32Encode(bytes: Buffer): string {
  let bits = 0;
  let value = 0;
  let output = "";
  for (const byte of bytes) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      output += BASE32_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) {
    output += BASE32_ALPHABET[(value << (5 - bits)) & 31];
  }
  return output;
}

export function generateSetupPassword(): string {
  const raw = base32Encode(crypto.randomBytes(10));
  return raw.match(/.{1,5}/g)?.join("-") ?? raw;
}

/** True once a real admin identity exists — either through the bootstrap/recovery
 *  flow (app_meta) or (legacy) both ADMIN_USERNAME/ADMIN_PASSWORD_HASH set via env.
 *  The env case matters so an install that predates this flow (this dev host
 *  included) is never forced through a fresh bootstrap just because it hasn't
 *  written installation_initialized yet. */
export function isInitialized(): boolean {
  const db = getDatabase();
  const row = db.prepare("SELECT value FROM app_meta WHERE key = ?").get(INSTALLATION_INITIALIZED_KEY) as { value: string } | undefined;
  if (row?.value === "true") return true;
  return !!(config.adminUsername && config.adminPasswordHash);
}

export function getActiveAdminUsername(): string | null {
  const row = getDatabase().prepare("SELECT value FROM app_meta WHERE key = ?").get(ADMIN_USERNAME_KEY) as { value: string } | undefined;
  return row?.value ?? config.adminUsername;
}

export function markInitialized(username: string, passwordHash: string): void {
  const db = getDatabase();
  const now = new Date().toISOString();
  const upsert = db.prepare(`
    INSERT INTO app_meta (key, value, updated_at) VALUES (?, ?, ?)
    ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
  `);
  upsert.run(ADMIN_USERNAME_KEY, username, now);
  upsert.run("admin_password_hash", passwordHash, now);
  upsert.run(INSTALLATION_INITIALIZED_KEY, "true", now);
}

function invalidateUnconsumed(kind: SetupCredentialKind): void {
  getDatabase()
    .prepare("DELETE FROM setup_credentials WHERE kind = ? AND consumed_at IS NULL")
    .run(kind);
}

function insertCredential(kind: SetupCredentialKind, username: string, password: string, ttlMs: number): void {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + ttlMs).toISOString();
  getDatabase()
    .prepare(`
      INSERT INTO setup_credentials (kind, username, password_hash, created_at, expires_at)
      VALUES (?, ?, ?, ?, ?)
    `)
    .run(kind, username, bcrypt.hashSync(password, 12), now.toISOString(), expiresAt);
}

/** Idempotent, called once at boot (src/index.ts). No-op once initialized or if an
 *  unconsumed bootstrap credential already exists. Prefers a plaintext credential
 *  generated by stackport.sh (ADMIN_BOOTSTRAP_USERNAME/PASSWORD in secrets.env,
 *  printed to the operator's terminal there — see stackport.sh's ensure_secrets) so
 *  the app itself never needs to reveal a generated secret over any channel. Falls
 *  back to generating and printing one itself (once, to stdout) for direct
 *  `docker compose up` use without going through stackport.sh (e.g. this dev host). */
export function ensureBootstrapCredential(): void {
  if (isInitialized()) return;

  const existing = getDatabase()
    .prepare("SELECT id FROM setup_credentials WHERE kind = 'bootstrap' AND consumed_at IS NULL AND expires_at > ?")
    .get(new Date().toISOString());
  if (existing) return;

  const envUsername = process.env["ADMIN_BOOTSTRAP_USERNAME"];
  const envPassword = process.env["ADMIN_BOOTSTRAP_PASSWORD"];
  if (envUsername && envPassword) {
    invalidateUnconsumed("bootstrap");
    insertCredential("bootstrap", envUsername, envPassword, BOOTSTRAP_CREDENTIAL_TTL_MS);
    return;
  }

  const username = "admin";
  const password = generateSetupPassword();
  invalidateUnconsumed("bootstrap");
  insertCredential("bootstrap", username, password, BOOTSTRAP_CREDENTIAL_TTL_MS);
  // eslint-disable-next-line no-console
  console.log(
    `[installation] Generated one-time bootstrap credential (expires in 24h):\n` +
    `[installation]   Username: ${username}\n` +
    `[installation]   Password: ${password}\n` +
    `[installation] Log in and complete setup to create your real administrator account.`
  );
}

/** Used by both routes/setup.ts (login) and cli/adminRecovery.ts (generation) —
 *  the single source of truth for "is this the currently-active credential of
 *  this kind". */
export function findActiveCredential(kind: SetupCredentialKind): SetupCredentialRow | undefined {
  return getDatabase()
    .prepare("SELECT * FROM setup_credentials WHERE kind = ? AND consumed_at IS NULL AND expires_at > ? ORDER BY id DESC LIMIT 1")
    .get(kind, new Date().toISOString()) as SetupCredentialRow | undefined;
}

export function consumeCredential(id: number): void {
  getDatabase()
    .prepare("UPDATE setup_credentials SET consumed_at = ? WHERE id = ?")
    .run(new Date().toISOString(), id);
}

/** Invoked by cli/adminRecovery.ts (via `stackport admin-recovery` -> docker exec) —
 *  never by an HTTP route. Invalidates any unconsumed recovery credential first, so
 *  only one is ever live. */
export function createRecoveryCredential(): { username: string; password: string } {
  const username = "recovery";
  const password = generateSetupPassword();
  invalidateUnconsumed("recovery");
  insertCredential("recovery", username, password, RECOVERY_CREDENTIAL_TTL_MS);
  return { username, password };
}
