import { useState, useEffect, type FC } from "react";
import { useNavigate } from "react-router-dom";
import { GitCommitHorizontal, Globe2, KeyRound, Lock, Rocket, Server, User } from "lucide-react";
import { api, setToken, isAuthenticated, setSetupToken, clearSetupToken } from "../api/client";
import { ApiError } from "../api/client";
import { StackPortBrand, StackPortWordmark } from "../logo/StackPortBrand";
import styles from "./Login.module.scss";
import StackPortLoading from "@/components/StackPortLoading";

// "login" is the normal path. The other three are the one-time setup flow
// (routes/setup.ts): "setup-login" accepts the bootstrap/recovery credential
// generated by stackport.sh's ensure_secrets or `stackport admin-recovery`;
// "setup-create-admin" (first install) and "setup-recovery" (locked-out admin)
// both let the operator choose their own real username+password, then hand back
// to the normal login form. Kept as one component/route rather than a separate
// page — the two flows share almost all of their form/field UI.
type Mode = "checking" | "login" | "setup-login" | "setup-create-admin" | "setup-recovery";

const Login: FC = () => {
  const navigate = useNavigate();

  const [mode, setMode] = useState<Mode>("checking");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(false);

  const [setupUsername, setSetupUsername] = useState("");
  const [setupPassword, setSetupPassword] = useState("");
  const [setupConfirm, setSetupConfirm] = useState("");

  useEffect(() => {
    if (isAuthenticated()) {
      navigate("/projects", { replace: true });
      return;
    }
    api.getSetupStatus()
      .then((status) => setMode(status.initialized ? "login" : "setup-login"))
      .catch(() => setMode("login"));
  }, [navigate]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const { token } = await api.login(username, password);
      setToken(token);
      navigate("/projects", { replace: true });
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Login failed");
    } finally {
      setLoading(false);
    }
  }

  async function handleSetupLogin(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const result = await api.setupLogin(username, password);
      setSetupToken(result.token);
      setUsername("");
      setPassword("");
      setMode(result.kind === "recovery" ? "setup-recovery" : "setup-create-admin");
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Invalid setup credential");
    } finally {
      setLoading(false);
    }
  }

  async function handleCreateAdmin(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    if (setupPassword !== setupConfirm) {
      setError("Passwords do not match.");
      return;
    }
    if (setupPassword.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }
    setLoading(true);
    try {
      if (mode === "setup-recovery") {
        await api.setupRecovery(setupUsername, setupPassword);
      } else {
        await api.setupCreateAdmin(setupUsername, setupPassword);
      }
      clearSetupToken();
      setSetupUsername("");
      setSetupPassword("");
      setSetupConfirm("");
      setNotice(
        mode === "setup-recovery"
          ? "Administrator access restored. Log in with your new credentials."
          : "Administrator account created. Log in with your new credentials."
      );
      setMode("login");
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to save administrator credentials");
    } finally {
      setLoading(false);
    }
  }

  const heroPanel = (
    <section className={styles.heroPanel} aria-label="STACKPORT overview">
      <div className={styles.heroBrand}>
        <StackPortBrand
          className={styles.heroIcon}
          iconSize={78}
          showWordmark={false}
        />
        <div>
          <p className={styles.kicker}>VPS Manager</p>
          <h1>
            <StackPortWordmark className={styles.heroWordmark} />
          </h1>
        </div>
      </div>
      <p className={styles.heroCopy}>
        Focus one VPS into a clean project hub: configure multiple apps,
        route subdomains, store credentials, and auto-deploy on commit.
      </p>
      <div className={styles.signalGrid}>
        <span><Server size={15} />One VPS</span>
        <span><Globe2 size={15} />Subdomains</span>
        <span><GitCommitHorizontal size={15} />Commit deploys</span>
        <span><Rocket size={15} />Projects</span>
      </div>
    </section>
  );

  return (
    <div className={styles.loginWrap}>
      <StackPortLoading show={mode === "checking"} />
      {heroPanel}
      <div className={styles.loginCard}>
        <div className={styles.loginIcon}>
          <StackPortBrand iconSize={48} showWordmark={false} />
        </div>
        <h2 className={styles.loginTitle}>
          <StackPortWordmark />
        </h2>

        {mode === "login" && (
          <>
            <p className={styles.loginSub}>VPS Manager</p>
            {error && <div className="alert alert-error">{error}</div>}
            {notice && <div className="alert alert-success">{notice}</div>}
            <form onSubmit={handleSubmit}>
              <div className="field">
                <label htmlFor="username">
                  <User size={12} />
                  Username
                </label>
                <input
                  id="username"
                  type="text"
                  autoComplete="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="field">
                <label htmlFor="password">
                  <Lock size={12} />
                  Password
                </label>
                <input
                  id="password"
                  type="password"
                  autoComplete="current-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
                {loading ? "Logging in..." : "Login"}
              </button>
            </form>
          </>
        )}

        {mode === "setup-login" && (
          <>
            <p className={styles.loginSub}>First-time setup — enter your one-time credential</p>
            {error && <div className="alert alert-error">{error}</div>}
            <form onSubmit={handleSetupLogin}>
              <div className="field">
                <label htmlFor="setup-login-username">
                  <User size={12} />
                  Username
                </label>
                <input
                  id="setup-login-username"
                  type="text"
                  autoComplete="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="field">
                <label htmlFor="setup-login-password">
                  <KeyRound size={12} />
                  One-time password
                </label>
                <input
                  id="setup-login-password"
                  type="password"
                  autoComplete="off"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
                {loading ? "Checking..." : "Continue"}
              </button>
            </form>
            <span className="hint">
              Printed once by <code>stackport.sh</code> when this install was created.
            </span>
          </>
        )}

        {(mode === "setup-create-admin" || mode === "setup-recovery") && (
          <>
            <p className={styles.loginSub}>
              {mode === "setup-recovery" ? "Set new administrator credentials" : "Create your administrator account"}
            </p>
            {error && <div className="alert alert-error">{error}</div>}
            <form onSubmit={handleCreateAdmin}>
              <div className="field">
                <label htmlFor="new-admin-username">
                  <User size={12} />
                  Username
                </label>
                <input
                  id="new-admin-username"
                  type="text"
                  autoComplete="username"
                  value={setupUsername}
                  onChange={(e) => setSetupUsername(e.target.value)}
                  required
                />
              </div>
              <div className="field">
                <label htmlFor="new-admin-password">
                  <Lock size={12} />
                  Password
                </label>
                <input
                  id="new-admin-password"
                  type="password"
                  autoComplete="new-password"
                  value={setupPassword}
                  onChange={(e) => setSetupPassword(e.target.value)}
                  required
                />
              </div>
              <div className="field">
                <label htmlFor="new-admin-confirm">
                  <Lock size={12} />
                  Confirm password
                </label>
                <input
                  id="new-admin-confirm"
                  type="password"
                  autoComplete="new-password"
                  value={setupConfirm}
                  onChange={(e) => setSetupConfirm(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className="btn btn-primary btn-full" disabled={loading}>
                {loading ? "Saving..." : "Save and continue"}
              </button>
            </form>
          </>
        )}
      </div>
    </div>
  );
};

export default Login;
